name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: flask-api-459518
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/flask-api-459518/em-flask-api:latest .
        docker push gcr.io/flask-api-459518/em-flask-api:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy em-flask-api \
          --image gcr.io/flask-api-459518/em-flask-api:latest \
          --region europe-west2 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars FLASK_DEBUG=1

