name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: flask-api-459518

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/flask-api-459518/em-flask-api:latest .
        docker push gcr.io/flask-api-459518/em-flask-api:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy em-flask-api \
          --image gcr.io/flask-api-459518/em-flask-api:latest \
          --region europe-west2 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars FLASK_DEBUG=1
